apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-database-pvc
  labels:
    app: filebrowser
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-fast-ssd