apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openclaw-gateway-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx-ingress-controller
  tls:
  - hosts:
    - openclaw.amanises.local
    secretName: openclaw-tls
  rules:
  - host: openclaw.amanises.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openclaw
            port:
              number: 18789
  - host: filebrowser.amanises.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openclaw
            port:
              number: 8080